require: 
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

RSpec/SubjectStub:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/registration_stage_console_spec.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageChain:
  Enabled: false
